
//
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
//

using System.Reflection;


[assembly: AssemblyTitle("LiveCaptions Translator")]
[assembly: AssemblyVersion("1.8.1304.1311")]
[assembly: AssemblyFileVersion("1.8.1304.1311")]